name: Print Code Change

on: 
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run checkstyle
        run: echo "Code changed"